### ISSUE TITLE
Compatible R version

### ISSUE THREAD

**Issue by dfernandezperez** [snystrom/memes#77]
Dear @snystrom,

I've just found these very nice wrappers around the MEME suit and I wanted to give them a try. I have tried to install them but the installation tells me that at least R 4.1 is required. Since that R version is not the official release, I was wondering if this is an error I am experiencing or indeed R >= 4.1 is required to installe your package. 

Sorry for opening an issue for this, I would prefer to send and e-mail but I wasn't able to find it!

Thanks a lot,

Daniel

**Comment by snystrom** [comment]
Hi Daniel, 

Sorry for the inconvenience. I'll be submitting this to bioconductor soon and their devel branch requires depending on R 4.1. In the mean time, I created a new branch called `no-r-4` which you can install using:

`remotes::install_github("snystrom/memes", ref = "no-r-4")`

This should install everything for you without causing the error. The package runs fine pre-4.0.

You may also try the docker container like so, but this will use a new R version so I wouldn't suggest it if you're trying to use the package in an existing analysis.
```
docker pull snystrom/memes_docker:devel
docker run -e PASSWORD=<password> -p 8787:8787 -v <path>/<to>/<project>:/mnt/<project> snystrom/memes_docker:devel
```

Thanks for trying the package. I am always eager to hear how you like it, so please feel free to send feedback or submit issues if you have problems, ideas, or something in the documentation is confusing.

Feel free to close this issue if it resolves your problem, and if not, let me know and I'll try to get something working for you.

**Comment by dfernandezperez** [comment]
Hey!

Sure, I understand. The docker image is indeed a very nice solution, but as you said I have already my own docker image with rstudio and all the packages and software I use for my workflow, so using another image just to run your wrappers for already started projects wouldn't be ideal. 

Anyway, thanks a lot for giving me the chance to try memes, I have already installed it and I am very excited to add it into my workflow!

Best,

Daniel

**Comment by snystrom** [comment]
Hey, I just did a significant upgrade to memes (see the NEWS.md for release notes). This one's going to bioconductor soon. I went ahead and pushed the changes to the `no-r-4` branch as well so if you want to update it's there for you.

The major gist of the upgrade is using a slightly different output format that has more compatability with universalmotif. The `as_universalmotif_df` and related functions are removed in favor of new `to_df` and `to_list()` that now work in base `universalmotif`. Also, I changed the default `dist` parameter for TomTom from `pearson` to `ed`. So that could affect results if you're using the default parameters.

If you've already got an analysis working, I wouldn't upgrade otherwise there will be some bugs related to these changes you'll need to fix, but just in case you want the new features, you can get them!

Cheers.

**Comment by dfernandezperez** [comment]
Thanks a lot! I will try the new version for the new analyses, by now I am super happy with the results I am obtaining. Very useful to be able to integrate this tools directly into my R workflow ;)!

Keep it up!

Cheers
