### ISSUE TITLE
Error: Column `rc` doesn't exist.

### ISSUE THREAD

**Issue by pbouvrette** [snystrom/memes#89]
Hi @snystrom. Thank you for the memes packages. When executing runTomTom(motif, norc = T) I get `Error: Can't subset columns that don't exist. Column `rc` doesn't exist. `How can I execute runTomTom without scoring reverse complement of motif? Thank you for your help!

**Comment by snystrom** [comment]
Oh no, that's a bug! Thanks for reporting & sorry for the issue.

I'm pretty sure I know how to fix this, but can't get to it tonight. I'll try to get a fix by tomorrow afternoon & ping you again here.

Just as a quick note to myself, I think the error is here:
https://github.com/snystrom/memes/blob/9a52d783bb1cc5a9b5a0810414ac9d9d0f81ab4b/R/tomtom.R#L356

Instead I need to only drop this column if it exists.

Also, need to add a unit test to catch this in the future.

**Comment by snystrom** [comment]
Hey, this should be resolved now. You can use the development branch from github using: `remotes::install_github("snystrom/memes")`, or you can wait a day or two to get the bugfix release directly from Bioconductor. I suggest just using the development version since it is identical to the release version, you won't have any bugs or different behavior. It just takes a few days for the new version to show up on Bioconductor servers.

Please reopen the issue if this doesn't fix it for you. Hope the package is useful!

**Comment by snystrom** [comment]
Welp, this isn't fixed, sorry. My automated tests just caught something that didn't trigger locally, so I'm investigating.

**Comment by snystrom** [comment]
Ok, this should be fixed for real now!

**Comment by pbouvrette** [comment]
It is indeed! Thank you very much for you quick response and work correcting the issue. It is much appreciated.
